addpkg: nix
archlinuxcn/repo pull request #2092
Opened 2021-02-12 12:43 UTC by berberman

nix can be used as an external package manager on Arch Linux.

2021-02-17 12:11 UTC, DuckSoft requested changes
Dear Sir or Madam,

I'd appreciate your efforts on pushing `nix` into `archlinuxcn`, but you have to resolve the following problem first:
1. `editline` (https://aur.archlinux.org/packages/editline/) is an AUR dependency and should be also packaged if you want to package `nix`.
2. `archlinux-nix` (https://aur.archlinux.org/packages/archlinux-nix/) is another AUR optional dependency and, in this case, I would also recommend you to port this package.

Finally, do not forget to put `repo_depends` if this package has dependencies inside `archlinuxcn`. Thanks again!

2021-03-28 11:58 UTC, DuckSoft commented
@berberman 

sorry to bother but, it's been around 45 days since you first submitted this pull request. 
i wonder if you still want to make it available in `archlinuxcn` repository.

- if you want to continue, please fix the package according to our review.
- if you want to discard it, please close this pull request.

thanks in advance.

2021-03-28 12:52 UTC, berberman commented
Sorry for the delay, and thanks for following up. I will fix it as fast as possible.

2021-03-30 05:29 UTC, berberman commented
@DuckSoft I've applied your suggestions, please take a look. Many thanks!

2021-03-30 05:46 UTC, DuckSoft commented
Your `lilac.yaml`s show that the packages are simply following AUR changes. However, neither AUR package maintainers nor archlinuxcn package maintainer (you) are archlinuxcn trusted members. I know "following the upstream" sounds a great plan, but this could bring unforeseen circumstances, like, someone added a rm -rf /home in install.sh. 

Copying PKGBUILD from AUR itself is not problematic --- blindly following any changes that upstream made is. You may want to replace your pre_build and post_build hook functions and update checker to upstream releases accordingly.

2021-07-02 10:45 UTC, yan12125 commented
nix is now in [community]: https://archlinux.org/packages/community/x86_64/nix/

2021-07-02 10:45 UTC, closed without merging