fix: remove `npm --user root`
archlinuxcn/repo pull request #2629
Opened 2022-01-18 01:18 UTC by ouuan

Since npm 7, the `--user` option is no longer available. `--user root` not only doesn't fix the permission problem, but also installs the package called "root", which conflicts with other packages that also have the `--user root` option.

2022-01-18 02:35 UTC, imlonghao requested changes
`joplin` is following AUR package and your change will not effect, meanwhile, it's broken at this time. (#2611)

2022-01-19 00:54 UTC, ouuan commented
> [SilverRainZ](/SilverRainZ) added the [ upstream issue ](https://github.com/archlinuxcn/repo/issues?q=is%3Aopen+label%3A%22upstream+issue%22+sort%3Aupdated-desc) label

We can ignore joplin in this PR.

2022-01-19 02:50 UTC, SilverRainZ commented
> We can ignore joplin in this PR.

Okay, I removed the label.

2022-01-23 12:27 UTC, SilverRainZ commented
@im

2022-01-24 14:04 UTC, imlonghao approved these changes
LGTM

2022-01-24 14:05 UTC, merged