Add clash-verge
archlinuxcn/repo pull request #2921
Opened 2022-09-24 13:26 UTC by sukanka

This is a PKGBUILD that build clash-verge from source
see https://github.com/archlinuxcn/repo/issues/2885#issuecomment-1252484229

2022-09-25 14:13 UTC, SilverRainZ requested changes
在 cn 源里的包需要添加一个 lilac.yaml 来描述维护者信息以及如何更新这个包。可以参考 archlinuxcn/ 目录下的其他包。

2022-09-25 14:22 UTC, sukanka commented
> 在 cn 源里的包需要添加一个 lilac.yaml 来描述维护者信息以及如何更新这个包。可以参考 archlinuxcn/ 目录下的其他包。

我不是 archlinuxcn 的维护者呀，我应该不需要写 `lilac.yaml` 吧，应该是决定接手的维护者来写吧。

2022-09-25 15:40 UTC, lilydjwg commented
On Sun, Sep 25, 2022 at 07:22:40AM -0700, sukanka wrote:
> > 在 cn 源里的包需要添加一个 lilac.yaml 来描述维护者信息以及如何更新这个包。可以参考 archlinuxcn/ 目录下的其他包。
> 
> 我不是 archlinuxcn 的维护者呀，我应该不需要写 `lilac.yaml` 吧，应该是决定接手的维护者来写吧。

要的。你 pr 的包，当然你也要收错误报告并及时修复它们。

-- 
Best regards,
lilydjwg

2022-09-26 01:15 UTC, sukanka commented
不清楚是不是少写了依赖，用 `makepkg` 构建能过，用 `extra-x86_64-build` 构建会遇到错误，见 https://fars.ee/Q5xG
```bash
extra-x86_64-build  -r /tmp/arch-chroot -- -I clash-geoip-20220912-1-any.pkg.tar.zst -I clash-meta-bin-1.13.1-0-x86_64.pkg.tar.zst -I clash-premium-bin-2022.08.26-1-x86_64.pkg.tar.zst 
```

2022-09-26 02:24 UTC, SilverRainZ commented
> 不清楚是不是少写了依赖，用 `makepkg` 构建能过，用 `extra-x86_64-build` 构建会遇到错误，见 https://fars.ee/Q5xG
> 
> ```shell
> extra-x86_64-build  -r /tmp/arch-chroot -- -I clash-geoip-20220912-1-any.pkg.tar.zst -I clash-meta-bin-1.13.1-0-x86_64.pkg.tar.zst -I clash-premium-bin-2022.08.26-1-x86_64.pkg.tar.zst 
> ```

看起来似乎是缺少了 quickjs？

2022-09-26 02:29 UTC, sukanka commented
> 看起来似乎是缺少了 quickjs？

我测试过，加了 quickjs 还是这样，而且我用 makepkg 的时候，我本机上没有 quickjs. 也参考过 [clash-verge-bin](https://aur.archlinux.org/packages/clash-verge-bin), 添加过 `'libappindicator-gtk3' 'webkit2gtk' 'gtk3' 'libayatana-appindicator'` 到依赖里面，仍然是同样的错误。

甚至在 chroot 的  `/usr/lib/` 下检查过 `cc` 时候用到的库，一个都不缺。

2022-09-26 02:54 UTC, sukanka commented
> 看起来似乎是缺少了 quickjs？

 OK 了，还真是缺  quickjs，之前忘了加 `RUSTFLAGS`

2022-09-27 02:08 UTC, imlonghao commented
依赖 archlinuxcn 的包 (clash-premium-bin) 需要给 lilac.yaml 加上 `repo_depends`

2022-09-27 02:28 UTC, sukanka commented
> 依赖 archlinuxcn 的包 (clash-premium-bin) 需要给 lilac.yaml 加上 `repo_depends`

那要是没在 archlinuxcn 里面的包，比如 quickjs， 是不是要一起提交上来？

2022-09-27 02:49 UTC, lilydjwg commented
> 那要是没在 archlinuxcn 里面的包，比如 quickjs， 是不是要一起提交上来？

是啊。

2022-10-02 13:19 UTC, yuyichao commented on archlinuxcn/clash-verge/lilac.yaml
> +  - github: sukanka
GitHub 上有邮箱不够么？

2022-10-02 13:27 UTC, SilverRainZ commented on archlinuxcn/clash-verge/lilac.yaml
> +  - github: sukanka
没有填的话会根据 github 的邮箱发是么？那就没问题。

2022-10-02 14:24 UTC, SilverRainZ approved these changes

2022-10-03 13:38 UTC, merged