Add lceda-pro-bin
archlinuxcn/repo pull request #2981
Opened 2022-10-27 09:34 UTC by taotieren

2022-10-27 10:33 UTC, MarvelousBlack commented
> 六、知识产权声明
　　（1）嘉立创EDA所提供的网络服务的相关著作权、专利权、商标、商业秘密及其它任何所有权或权利，均属嘉立创EDA所有。非经嘉立创EDA的同意，任何人或用户均不得擅自下载、复制、传输、改编、编辑，否则应负所有法律责任。
（2）嘉立创EDA拥有向用户提供网络服务过程中所产生并储存于服务器中的任何数据信息的所有权。
（3）任何人或企业未经嘉立创EDA书面许可，不得对嘉立创EDA以及嘉立创EDA官方库文件进行二次改造、销售，或包含在对外销售的数据包中。

2022-10-28 01:16 UTC, taotieren commented
> > 六、知识产权声明
> > 　　（1）嘉立创EDA所提供的网络服务的相关著作权、专利权、商标、商业秘密及其它任何所有权或权利，均属嘉立创EDA所有。非经嘉立创EDA的同意，任何人或用户均不得擅自下载、复制、传输、改编、编辑，否则应负所有法律责任。
> > （2）嘉立创EDA拥有向用户提供网络服务过程中所产生并储存于服务器中的任何数据信息的所有权。
> > （3）任何人或企业未经嘉立创EDA书面许可，不得对嘉立创EDA以及嘉立创EDA官方库文件进行二次改造、销售，或包含在对外销售的数据包中。

已经在和 LCEDA Linux 项目负责人沟通分发授权的问题了。
现在是他们那边正在谈论这个分发授权的具体事宜。

2022-11-02 05:40 UTC, taotieren commented
@MarvelousBlack LCEDA 是官网发布的更新，该如何配置 lilac 检测更新呢？谢谢

2022-11-02 14:00 UTC, hubutui commented
如果可以分发的话，一般这种闭源的软件包，也没有必要用 `-bin` 吧。你看看 wps 就直接叫 `wps-office`，不会叫 `wps-office-bin`。说起来 wps 已经不在源里了，可惜啊。

2022-11-03 06:29 UTC, taotieren commented
> 如果可以分发的话，一般这种闭源的软件包，也没有必要用 `-bin` 吧。你看看 wps 就直接叫 `wps-office`，不会叫 `wps-office-bin`。说起来 wps 已经不在源里了，可惜啊。

现在是他们法务部门在评估怎么出分发授权，预计这周有结果。

2022-11-03 08:34 UTC, MarvelousBlack commented
> > 如果可以分发的话，一般这种闭源的软件包，也没有必要用 `-bin` 吧。你看看 wps 就直接叫 `wps-office`，不会叫 `wps-office-bin`。说起来 wps 已经不在源里了，可惜啊。
> 
> 现在是他们法务部门在评估怎么出分发授权，预计这周有结果。带 `-bin` 或不带，问题也不是很大，最后安装的时候都是去掉了 `-bin` 信息了

抱歉，回复晚了点，因为这个需要他们先出分发授权我们才可以收录。如果添加这个包，那就需要得到他们的明确许可，先等他们讨论出来之后再考虑吧。


> @MarvelousBlack LCEDA 是官网发布的更新，该如何配置 lilac 检测更新呢？谢谢

lilac 的更新检出是基于 [nvchecker](https://github.com/lilydjwg/nvchecker) ，支持从网页获取更新，你可以在仓库里面翻看具体的用例。可以看看这个[ttf-babelstone-han 的 lilac.yaml](https://github.com/archlinuxcn/repo/blob/82c02419c70ec3fb4e5dc93c6bd581a6d2769850/archlinuxcn/ttf-babelstone-han/lilac.yaml) 如果这个也不满足，可以自己编写 lilac.py 来处理比较复杂的情况。

2022-11-08 06:44 UTC, taotieren commented
> > > 如果可以分发的话，一般这种闭源的软件包，也没有必要用 `-bin` 吧。你看看 wps 就直接叫 `wps-office`，不会叫 `wps-office-bin`。说起来 wps 已经不在源里了，可惜啊。
> > 
> > 
> > 现在是他们法务部门在评估怎么出分发授权，预计这周有结果。带 `-bin` 或不带，问题也不是很大，最后安装的时候都是去掉了 `-bin` 信息了
> 
> 抱歉，回复晚了点，因为这个需要他们先出分发授权我们才可以收录。如果添加这个包，那就需要得到他们的明确许可，先等他们讨论出来之后再考虑吧。
> 
> > @MarvelousBlack LCEDA 是官网发布的更新，该如何配置 lilac 检测更新呢？谢谢
> 
> lilac 的更新检出是基于 [nvchecker](https://github.com/lilydjwg/nvchecker) ，支持从网页获取更新，你可以在仓库里面翻看具体的用例。可以看看这个[ttf-babelstone-han 的 lilac.yaml](https://github.com/archlinuxcn/repo/blob/82c02419c70ec3fb4e5dc93c6bd581a6d2769850/archlinuxcn/ttf-babelstone-han/lilac.yaml) 如果这个也不满足，可以自己编写 lilac.py 来处理比较复杂的情况。

谢谢，我晚点研究下，要是不懂的话还会问你们的

2022-11-24 08:37 UTC, taotieren commented
@MarvelousBlack 
有空的话可以帮忙看看这份授权文件有没有什么需要补充的内容，
已反馈的问题：
- GNU/Linux 拼写错误

[【定稿】嘉立创EDA-Linux分发授权许可协议-20221124.docx](https://github.com/archlinuxcn/repo/files/10082160/EDA-Linux.-20221124.docx)

2022-11-24 08:39 UTC, oldherl commented
> @MarvelousBlack 有空的话可以帮忙看看这份授权文件有没有什么需要补充的内容， 已反馈的问题：
> 
>     * GNU/Linux 拼写错误
> 
> 
> [【定稿】嘉立创EDA-Linux分发授权许可协议-20221124.docx](https://github.com/archlinuxcn/repo/files/10082160/EDA-Linux.-20221124.docx)

GNU都拼成滚了

2022-11-28 11:48 UTC, taotieren commented
@MarvelousBlack 授权分发文件已添加，什么时候可以合并呢？

2022-11-28 16:05 UTC, hubutui commented
建议把多个 commit 合并一下吧。授权分发文件好像是要发到邮箱去备份来着？

2022-11-28 16:23 UTC, MarvelousBlack commented
> @MarvelousBlack 有空的话可以帮忙看看这份授权文件有没有什么需要补充的内容， 已反馈的问题：
> 
> * GNU/Linux 拼写错误
> 
> [【定稿】嘉立创EDA-Linux分发授权许可协议-20221124.docx](https://github.com/archlinuxcn/repo/files/10082160/EDA-Linux.-20221124.docx)

这份文件在哪公告？可以直接在立创eda那找到吗？

2022-11-28 16:25 UTC, MarvelousBlack requested changes
这里拆的bin包有什么意义？

2022-11-29 03:42 UTC, taotieren commented
> > @MarvelousBlack 有空的话可以帮忙看看这份授权文件有没有什么需要补充的内容， 已反馈的问题：
> > 
> > * GNU/Linux 拼写错误
> > 
> > [【定稿】嘉立创EDA-Linux分发授权许可协议-20221124.docx](https://github.com/archlinuxcn/repo/files/10082160/EDA-Linux.-20221124.docx)
> 
> 这份文件在哪公告？可以直接在立创eda那找到吗？

已经内置在软件包中了，下载后可以看到相应的授权文件。这里只是在仓库存档了一份。

2022-11-29 03:44 UTC, taotieren commented
> 这里拆的bin包有什么意义？

兼容之前的 -bin 的包。不然又得在新开一个 lceda-pro 包仓库。目前是是兼容 lceda-pro-bin 的包，lceda-pro-bin 是一个空包，是以来 lceda-pro

2022-11-29 03:46 UTC, taotieren commented
> 建议把多个 commit 合并一下吧。授权分发文件好像是要发到邮箱去备份来着？

是发到那个邮箱呢？方便提供下邮箱地址吗？我发送的时候同时抄送一份给 lceda 那边。

2022-11-29 03:46 UTC, taotieren commented
后面还有一个 easy-eda 的包也要加入进去。

2022-11-29 04:35 UTC, MarvelousBlack commented
> @MarvelousBlack 有空的话可以帮忙看看这份授权文件有没有什么需要补充的内容， 已反馈的问题：
> 
> * GNU/Linux 拼写错误
> 
> [【定稿】嘉立创EDA-Linux分发授权许可协议-20221124.docx](https://github.com/archlinuxcn/repo/files/10082160/EDA-Linux.-20221124.docx)

这个还有个问题
> 未经嘉立创EDA事先书面批准，向任何第三方披露本软件的任何基准测试的结果；

这个这种使用上的怎么不是写在主协议里面，而是写在分发授权协议里面。



> > > @MarvelousBlack 有空的话可以帮忙看看这份授权文件有没有什么需要补充的内容， 已反馈的问题：
> > > 
> > > * GNU/Linux 拼写错误
> > > 
> > > [【定稿】嘉立创EDA-Linux分发授权许可协议-20221124.docx](https://github.com/archlinuxcn/repo/files/10082160/EDA-Linux.-20221124.docx)
> > 
> > 
> > 这份文件在哪公告？可以直接在立创eda那找到吗？
> 
> 已经内置在软件包中了，下载后可以看到相应的授权文件。这里只是在仓库存档了一份。

这个是在他提供的那个 zip 包里面吗？有的话那就不需要在仓库存一份了。


> > 建议把多个 commit 合并一下吧。授权分发文件好像是要发到邮箱去备份来着？
> 
> 是发到那个邮箱呢？方便提供下邮箱地址吗？我发送的时候同时抄送一份给 lceda 那边。

同上，但看你这句话这个像是你出的文件？



> > 这里拆的bin包有什么意义？
> 
> 兼容之前的 -bin 的包。不然又得在新开一个 lceda-pro 包仓库。目前是是兼容 lceda-pro-bin 的包，lceda-pro-bin 是一个空包，是依赖 lceda-pro

那应该用 replaces 把那个 bin 包替换掉吧，而且不是像现在这样打个空包，而且这个包名，我觉得不需要用 -bin 吧。

> 后面还有一个 easy-eda 的包也要加入进去。

那就拆开来。  

你先 rebase 把 那好几条同一个包改动的 commit 都 squash 成一个然后 force push 吧，弄完我再看看吧，现在这样十几条，我也不方便看。

2022-11-29 06:38 UTC, taotieren commented
> > @MarvelousBlack 有空的话可以帮忙看看这份授权文件有没有什么需要补充的内容， 已反馈的问题：
> > 
> > * GNU/Linux 拼写错误
> > 
> > [【定稿】嘉立创EDA-Linux分发授权许可协议-20221124.docx](https://github.com/archlinuxcn/repo/files/10082160/EDA-Linux.-20221124.docx)
> 
> 这个还有个问题
> 
> > 未经嘉立创EDA事先书面批准，向任何第三方披露本软件的任何基准测试的结果；
> 
> 这个这种使用上的怎么不是写在主协议里面，而是写在分发授权协议里面。
Windows 和 macOS 他们是是按相应系统规范打包。Linux 没有按相应的系统打包，也没有提供相应的直接安装包。所以才对 Linux 发行版单独做了分发授权。
> 
> > > > @MarvelousBlack 有空的话可以帮忙看看这份授权文件有没有什么需要补充的内容， 已反馈的问题：
> > > > 
> > > > * GNU/Linux 拼写错误
> > > > 
> > > > [【定稿】嘉立创EDA-Linux分发授权许可协议-20221124.docx](https://github.com/archlinuxcn/repo/files/10082160/EDA-Linux.-20221124.docx)
> > > 
> > > 
> > > 这份文件在哪公告？可以直接在立创eda那找到吗？
> > 
> > 
> > 已经内置在软件包中了，下载后可以看到相应的授权文件。这里只是在仓库存档了一份。
> 
> 这个是在他提供的那个 zip 包里面吗？有的话那就不需要在仓库存一份了。
好的我后续删除掉也可以。使用 zip 包里面自带的一份。
> 
> > > 建议把多个 commit 合并一下吧。授权分发文件好像是要发到邮箱去备份来着？
> > 
> > 
> > 是发到那个邮箱呢？方便提供下邮箱地址吗？我发送的时候同时抄送一份给 lceda 那边。
> 
> 同上，但看你这句话这个像是你出的文件？
文件是他们出，需要的话我可以联系他们相应的工作人员发送这份分发授权文件。
> 
> > > 这里拆的bin包有什么意义？
> > 
> > 
> > 兼容之前的 -bin 的包。不然又得在新开一个 lceda-pro 包仓库。目前是是兼容 lceda-pro-bin 的包，lceda-pro-bin 是一个空包，是依赖 lceda-pro
> 
> 那应该用 replaces 把那个 bin 包替换掉吧，而且不是像现在这样打个空包，而且这个包名，我觉得不需要用 -bin 吧。
好的我修改下这部分的内容。
> 
> > 后面还有一个 easy-eda 的包也要加入进去。
> 
> 那就拆开来。
是的，先合并这个包后面在 PR 另外一个包。
> 
> 你先 rebase 把 那好几条同一个包改动的 commit 都 squash 成一个然后 force push 吧，弄完我再看看吧，现在这样十几条，我也不方便看。
已经 rebase

2022-11-30 02:04 UTC, Misaka13514 commented on archlinuxcn/lceda-pro/lilac.yaml
> +    xpath: "/html/body/div[1]/div[1]/div[4]/div[2]/table/tbody/tr[3]/td[2]/div[1]/span[1]"
```suggestion
    xpath: "/html/body/div[1]/div[1]/div[4]/div[2]/table/tbody/tr[3]/td[2]/div[1]/span[1]"
```
    xpath: "//table/tbody/tr[3]/td[2]/div/span[1]"

2022-11-30 02:10 UTC, Misaka13514 commented
我刚才发布了`1.9.20-2`，`PKGBUILD`和`LICENSE`需要更新。

2022-11-30 02:15 UTC, taotieren commented
> 我刚才发布了`1.9.20-2`，`PKGBUILD`和`LICENSE`需要更新。

内容是更新了，使用的还是 `1.9.20-1` 还没合并进去。自动更新的时候最后的 `-1` `-2` 是不会自动修改。这里手动指定了 `-1`. 还不确定什么时候能合并进去。

2022-11-30 02:17 UTC, Misaka13514 commented on archlinuxcn/lceda-pro/lilac.yaml
> +    xpath: "//table/tbody/tr[3]/td[2]/div/span[1]"
```suggestion
    xpath: "//table/tr[3]/td[2]/div/span[1]"
```
不好意思我刚才修改了一下建议，你可能没有看到，我发现HTML里没有`tbody`，这个应该是浏览器自动添加的，使用`htmlparser`的话我觉得应当删去。

2022-11-30 02:20 UTC, Misaka13514 commented
因为`1.9.20-2`添加了`aarch64`的支持，所以我不确定`lilac.yaml`是否还需要修改

2022-11-30 02:28 UTC, Misaka13514 commented
> 后面还有一个 easy-eda 的包也要加入进去。

我觉得对于CN用户来说可以先添加`lceda-bin`？

@yjun123 这位是`lceda-bin`的 maintainer

2022-11-30 03:48 UTC, Misaka13514 commented
@taotieren 请问 LCEDA Linux 项目的分发授权在打包时是否可以[使用系统的 electron](https://wiki.archlinux.org/title/Electron_package_guidelines#Using_the_system_electron)？有助于减小软件包体积。

```sh
electron /opt/lceda-pro/resources/app/
```

2022-11-30 05:17 UTC, Misaka13514 commented
> 后面还有一个 easy-eda 的包也要加入进去。

感觉没必要啊，我拿`lceda-pro`和`easyeda-pro`的`1.8.39`版本做比较：

```sh
$ diff easyeda-pro-linux-x64/ lceda-pro-linux-x64/
只在 easyeda-pro-linux-x64/ 存在：easyeda-pro
只在 easyeda-pro-linux-x64/ 存在：EasyEDA-PRO.dkt
easyeda-pro-linux-x64/icon 和 lceda-pro-linux-x64/icon 有共同的子目录
只在 lceda-pro-linux-x64/ 存在：lceda-pro
只在 lceda-pro-linux-x64/ 存在：LCEDA-PRO.dkt
easyeda-pro-linux-x64/locales 和 lceda-pro-linux-x64/locales 有共同的子目录
easyeda-pro-linux-x64/resources 和 lceda-pro-linux-x64/resources 有共同的子目录
easyeda-pro-linux-x64/swiftshader 和 lceda-pro-linux-x64/swiftshader 有共同的子目录
```

基本上是一模一样的......

2022-11-30 09:29 UTC, taotieren commented
> > 后面还有一个 easy-eda 的包也要加入进去。
> 
> 我觉得对于CN用户来说可以先添加`lceda-bin`？
> 
> @yjun123 这位是`lceda-bin`的 maintainer

要看下 lceda 这个里面有没有分发授权文件，按 lc 那边的说法是 lceda 将逐渐用 lceda-pro 来替代。

2022-11-30 09:30 UTC, taotieren commented
> @taotieren 请问 LCEDA Linux 项目的分发授权在打包时是否可以[使用系统的 electron](https://wiki.archlinux.org/title/Electron_package_guidelines#Using_the_system_electron)？有助于减小软件包体积，对多架构的支持也就转移到 electron 上了。
> 
> ```shell
> $ diff lceda-pro-linux-arm64/ lceda-pro-linux-x64/
> 二进制文件 lceda-pro-linux-arm64/chrome_crashpad_handler 和 lceda-pro-linux-x64/chrome_crashpad_handler 不同
> 二进制文件 lceda-pro-linux-arm64/chrome-sandbox 和 lceda-pro-linux-x64/chrome-sandbox 不同
> lceda-pro-linux-arm64/icon 和 lceda-pro-linux-x64/icon 有共同的子目录
> 二进制文件 lceda-pro-linux-arm64/lceda-pro 和 lceda-pro-linux-x64/lceda-pro 不同
> 二进制文件 lceda-pro-linux-arm64/libEGL.so 和 lceda-pro-linux-x64/libEGL.so 不同
> 二进制文件 lceda-pro-linux-arm64/libffmpeg.so 和 lceda-pro-linux-x64/libffmpeg.so 不同
> 二进制文件 lceda-pro-linux-arm64/libGLESv2.so 和 lceda-pro-linux-x64/libGLESv2.so 不同
> 二进制文件 lceda-pro-linux-arm64/libvk_swiftshader.so 和 lceda-pro-linux-x64/libvk_swiftshader.so 不同
> 二进制文件 lceda-pro-linux-arm64/libvulkan.so.1 和 lceda-pro-linux-x64/libvulkan.so.1 不同
> lceda-pro-linux-arm64/locales 和 lceda-pro-linux-x64/locales 有共同的子目录
> lceda-pro-linux-arm64/resources 和 lceda-pro-linux-x64/resources 有共同的子目录
> 二进制文件 lceda-pro-linux-arm64/snapshot_blob.bin 和 lceda-pro-linux-x64/snapshot_blob.bin 不同
> 二进制文件 lceda-pro-linux-arm64/v8_context_snapshot.bin 和 lceda-pro-linux-x64/v8_context_snapshot.bin 不同
> ```
> 
> 可以看到不同的都是 electron 本体，使用以下命令 APP 也可以运行。
> 
> ```shell
> electron19 /opt/lceda-pro/resources/app/
> ```
> 
> 完整的 PKGBUILD 在[easyeda-pro-electron](https://aur.archlinux.org/packages/easyeda-pro-electron)，`Net Upgrade Size: -179.04 MiB`

是可以使用系统的 electron 文件，但是需要做深度修改，需要花比较大的精力验证。

2022-11-30 15:33 UTC, taotieren commented
> > 看了下你这边还可能需要补充 `libappindicator-gtk3`（待定） `libnotify`(需要)
> 
> 已添加。
> 
> > 能用最新版本的 `electron` 包来替代 `electron19` 吗？
> 
> 因为`easyeda-pro-bin`里的electron版本是19所以最初用了19，看了下用最新的electron也可以运行，已修改。
> 
> > 路径的话更适合用 `/usr/share/easyeda-pro/`
> 
> 看了下 `code`, `element-desktop`, `geogebra` 都在使用`/usr/lib`，暂未修改。

担心会合其他软件包的文件重名，建议是使用 `/usr/share/easyeda-pro`
我这边做了变更，内置语言文件删除是不影响打包和使用。

2022-11-30 15:40 UTC, Misaka13514 commented
> 担心会合其他软件包的文件重名，建议是使用 `/usr/share/easyeda-pro` 我这边做了变更，内置语言文件删除是不影响打包和使用。

不会重名的，因为有文件夹`/usr/lib/easyeda-pro`

2022-11-30 15:48 UTC, Misaka13514 commented
> 我这边做了变更，内置语言文件删除是不影响打包和使用。

包含`locales`是参考了[geogebra](https://archlinux.org/packages/community/x86_64/geogebra/)的PKGBUILD 🤔

2022-12-01 03:20 UTC, taotieren commented
> > 我这边做了变更，内置语言文件删除是不影响打包和使用。
> 
> 包含`locales`是参考了[geogebra](https://archlinux.org/packages/community/x86_64/geogebra/)的PKGBUILD 🤔

看了[electron 源码包](https://github.com/archlinux/svntogit-community/blob/packages/electron/trunk/PKGBUILD)发现是在 `/usr/lib/{pkgname}`
等新版本同步后我改一下

2022-12-01 08:36 UTC, Misaka13514 commented
> @Misaka13514 你那边多架构版本也要同步更新下。

因为在使用系统electron，所以每个架构的二进制包里面我需要的源文件都是一样的啊（正如我的`diff lceda-pro-linux-arm64/ lceda-pro-linux-x64/`），所以我就从`x86_64`来源打`any`的包，我觉得没问题？

2022-12-01 08:55 UTC, taotieren commented
> > @Misaka13514 你那边多架构版本也要同步更新下。
> 
> ~因为在使用系统electron，所以 `x86_64` 和 `arm64` 的二进制包里面我需要的源文件都是一样的啊（正如我的`diff lceda-pro-linux-arm64/ lceda-pro-linux-x64/`），所以我就从`x86_64`来源打`any`的包 ，我觉得没问题？~
> 
> 如果需要支持龙芯和申威，你的 electron 版本也需要修改：
> 
> * x86_64 和 aarch64：19.1.0
> * 龙芯：17.4.0
> * 申威：未知，目前没跟上最新版，`1.8.39`里自身版本`lceda-pro-linux-sw64/version`都没写对。
> 
> electron17 和最新的 electron 互换性好像不是很好

和 lceda 人员沟通后，了解到是他们使用 `electron 21.3.0`

2022-12-07 02:35 UTC, taotieren commented
@MarvelousBlack 什么时候能合并进仓库呢？

2022-12-07 03:05 UTC, hubutui commented on archlinuxcn/lceda-pro/PKGBUILD
> +    export LC_CTYPE="zh_CN.UTF-8"
这个为啥要设置啊？好像一般都不去改这个的吧．

2022-12-07 03:07 UTC, hubutui commented on archlinuxcn/lceda-pro/PKGBUILD
> +conflicts=(${pkgname})
这个写得有问题啊，一个当然会提供它本身，没有必要写的．但是你这里又写它跟自己冲突？

2022-12-08 02:55 UTC, hubutui commented on archlinuxcn/lceda-pro/PKGBUILD
> +replaces=(lceda-pro-bin)
archlinuxcn repo 里没有 `lceda-pro-bin` 这个包啊，为啥要 replace?

2022-12-08 03:01 UTC, hubutui commented on archlinuxcn/lceda-pro/PKGBUILD
> +    export LC_CTYPE="zh_CN.UTF-8"
这个一般应该要删掉啊．完全没有必要的一行．

2022-12-08 06:15 UTC, hubutui commented
```
lceda-pro W: Directory (usr/lib/lceda-pro/resources/app/assets/smt-ui/0.3.277.8bb6e0/zip-files) is empty
lceda-pro E: Dependency python detected and not included (libraries ['sys', 'tarfile', 'os'] needed in files ['usr/lib/lceda-pro/resources/app/node_modules/sqlite3/deps/extract.py'])
```
这个需要处理么？有个空的目录．然后还有个 python 脚本．我觉得还ok．

2022-12-08 07:07 UTC, taotieren commented
> ies ['sys', 'tarfile', 'os'] needed in files ['usr/lib/lceda-pro/resources/app/

这些对用户来说影响不大，暂时先这样，后面我再多验证下。

2022-12-11 13:37 UTC, hubutui commented on archlinuxcn/lceda-pro/lilac.yaml
> +    xpath: "//table/tr[3]/td[2]/div/span[1]"
可以试试这个：
```
- source: regex
  url: 'https://lceda.cn/page/download?src=index'
  regex: 'lceda-pro-linux-x64-(\d+.\d+.\d+).zip'
```

2022-12-12 15:19 UTC, hubutui commented on archlinuxcn/lceda-pro/PKGBUILD
> +conflicts=(${pkgname})
奇怪，咋又改回去了？`git push` 错了？

2022-12-14 07:04 UTC, taotieren commented
> > @Misaka13514 你那边多架构版本也要同步更新下。
> 
> 如果需要支持龙芯和申威，你的 electron 版本也需要修改：
> 
> * x86_64 和 aarch64：19.1.0
> * 龙芯：17.4.0
> * 申威：未知，目前没跟上最新版，`1.8.39`里自身版本`lceda-pro-linux-sw64/version`都没写对。
> 
> electron17 和最新的 electron 互换性好像不是很好，并且 [repo.archlinuxcn.org](https://repo.archlinuxcn.org) 没有龙芯和申威的`$arch` @taotieren
> 
> 如果不需要：
> 
> `x86_64` 和 `aarch64` 的二进制包里面构建需要的源文件通过对比是一样的。
> 
> [easyeda.com/page/download](https://easyeda.com/page/download) 上还没有开始分发多架构的软件包，我这边的包不急着修改

这个是其他架构的 Arch 发行版，他们会对不同架构进行修包处理。只要确定依赖包没问题，剩下的是不同架构的处理。

2023-01-18 09:14 UTC, MarvelousBlack commented on archlinuxcn/lceda-pro/PKGBUILD
> +provides=()
像这种 provides=() 里面空的建议删掉

2023-01-18 09:19 UTC, MarvelousBlack commented on archlinuxcn/lceda-pro/PKGBUILD
> +# prepare() {
这段注释不需要了吧

2023-01-29 09:06 UTC, taotieren commented
@lilydjwg 大佬，什么是方便加下仓库权限。

2023-01-29 09:48 UTC, MarvelousBlack approved these changes

2023-01-29 09:49 UTC, MarvelousBlack commented
ci 不通过，需要修一下

2023-01-29 10:22 UTC, taotieren commented
> ci 不通过，需要修一下

已修复。谢谢

2023-01-29 10:30 UTC, merged