Add opengnb
archlinuxcn/repo pull request #2994
Opened 2022-10-29 13:39 UTC by taotieren

2022-10-31 04:09 UTC, SilverRainZ requested changes

2022-10-31 04:09 UTC, SilverRainZ commented on archlinuxcn/opengnb/PKGBUILD
> +arch=('any')
编译型语言应当显式指明它支持的 arch。

2022-10-31 04:09 UTC, SilverRainZ commented on archlinuxcn/opengnb/PKGBUILD
> +arch=('any')
opengnb-git 也要改一下。

2022-10-31 04:09 UTC, SilverRainZ commented on archlinuxcn/opengnb/.gitignore
> +*
这个文件是误添加的么？

2022-10-31 06:03 UTC, taotieren commented on archlinuxcn/opengnb/.gitignore
> +*
好的，我删掉这个

2022-10-31 06:05 UTC, taotieren commented on archlinuxcn/opengnb/PKGBUILD
> +arch=('any')
> 编译型语言应当显式指明它支持的 arch。

已更新

2022-11-01 11:51 UTC, SilverRainZ commented
有了 -git 的话，这个包还需要么？看起来上游的更新并不是很频繁。

2022-11-01 12:42 UTC, taotieren commented
> 
上游更新会删 tag。有 发行版包，可以做个备份。

2022-11-02 01:26 UTC, taotieren commented
> 1. 什么样的上游更新会删 tag，应该反馈让他不删 tag

看 commit 记录是有发行版信息，看 tag 记录只有最新的 tag。
什么原因开发者还没回复

> 2. 备份可以 fork 自行备份，不需要加入仓库

atzlinux 那边有个仓库在同步进行 Debian 包的发行和维护，是有历史 tag ，但是版本会落后官方仓库几个版本。

2022-11-08 04:53 UTC, closed without merging