Add smiley-sans-git
archlinuxcn/repo pull request #3031
Opened 2022-11-15 14:08 UTC by taotieren

得意黑 Smiley Sans  开源字体开发版

2023-01-14 11:10 UTC, Y7n05h requested changes

2023-01-14 11:10 UTC, Y7n05h commented on archlinuxcn/smiley-sans-git/PKGBUILD
> +makedepends=(git python-brotli python-fontmake python-fonttools)
`python-fontmake` 包不在`官方源`或 `archlinuxcn` 源中。这个包依赖 `python-fontmake`，因此需要完成对 `python-fontmake` 的打包。

2023-01-14 11:10 UTC, Y7n05h commented on archlinuxcn/smiley-sans-git/lilac.yaml
> +build_prefix: extra-x86_64
```suggestion
build_prefix: archlinuxcn-x86_64
```

在 `archlinuxcn` 源加入 `python-fontmake` 后，需要通过 `archlinuxcn-x86_64` 来安装包含于 `archlinuxcn` 源中的依赖。

2023-01-26 16:19 UTC, taotieren commented on archlinuxcn/smiley-sans-git/lilac.yaml
> +build_prefix: extra-x86_64
已更新。谢谢。

2023-01-26 16:21 UTC, taotieren commented on archlinuxcn/smiley-sans-git/PKGBUILD
> +makedepends=(git python-brotli python-fontmake python-fonttools)
这个包你们这边方便提交吗？

2023-01-26 16:38 UTC, Y7n05h commented on archlinuxcn/smiley-sans-git/PKGBUILD
> +makedepends=(git python-brotli python-fontmake python-fonttools)
- 如果「这个包」是指 `python-fontmake`：fontmake 采用 [Apache-2.0 license](https://github.com/googlefonts/fontmake/blob/main/LICENSE) ，是自由软件，也可以自由分发。
- 如果「这个包」是指 `smiley-sans-git`： 得意黑采用 [OFL-1.1 license](https://github.com/atelier-anchor/smiley-sans/blob/main/LICENSE)，是自由软件且我没有查询到「得意黑」或者 「smiley sans」相关的有效商标，也可以自由分发。
因此无论 `smiley-sans-git` 还是 `python-fontmake` ~~大概~~都是可以提交的。

2023-01-27 12:20 UTC, taotieren commented on archlinuxcn/smiley-sans-git/PKGBUILD
> +makedepends=(git python-brotli python-fontmake python-fonttools)
已 PR 帮忙合并下：https://github.com/archlinuxcn/repo/pull/3128
谢谢。

2023-01-29 02:03 UTC, Y7n05h commented
看起来打包 `python-fontmake` 还需要在 archlinuxcn 源中添加 `python-fontmake` 的若干个依赖才能完成。
这或许有点繁琐。幸好 `python-fontmake` 只是 `makedepends`，因此可以尝试在打包 `smiley-sans-git` 时通过 pip 来安装 `fontmake`，就能从 `makedepends` 删除 `python-fontmake` 了。

2023-01-29 08:30 UTC, taotieren commented
> 看起来打包 `python-fontmake` 还需要在 archlinuxcn 源中添加 `python-fontmake` 的若干个依赖才能完成。 这或许有点繁琐。你可以添加 `python-fontmake` 的若干个依赖完成 `python-fontmake` 的打包或者采用下面的代替方法。 `python-fontmake` 只是 `makedepends`，因此可以尝试在打包 `smiley-sans-git` 时通过 pip 来安装 `fontmake`，就能从 `makedepends` 删除 `python-fontmake` 了。

我觉得还是补齐相应的依赖包，比第二种方式会更好点，这样的话，其他包如果想用的话，也会方便一点。

2025-03-12 03:50 UTC, taotieren commented
本地测试不通过，相关包已弃置。关闭此 PR

2025-03-12 03:50 UTC, closed without merging