Add waydroid
archlinuxcn/repo pull request #3090
Opened 2023-01-01 08:08 UTC by Puqns67

[waydroid](https://github.com/waydroid/waydroid), 一个在 wayland 环境下运行的安卓容器

2023-01-14 16:36 UTC, Y7n05h requested changes

2023-01-14 16:36 UTC, Y7n05h commented on archlinuxcn/libglibutil/PKGBUILD
> +depends=('glib2')
从 git 服务器 clone 需要编译时依赖 git。把链接改成下面这种，就不需要 clone 了。
https://github.com/sailfishos/libglibutil/archive/1.0.67.tar.gz
简写成 `${url}/archive/${pkgver}.tar.gz`
source 在这种情况下可以写成：
```
source=("${pkgver}-${pkgrel}.tar.gz"::"${url}/archive/${pkgver}.tar.gz")
```

2023-01-14 16:36 UTC, Y7n05h commented on archlinuxcn/libglibutil/lilac.yaml
> +
缺少 `pre_build` 和 `post_build`。

2023-01-14 16:36 UTC, Y7n05h commented on archlinuxcn/libgbinder/lilac.yaml
> +
缺少 `pre_build` 和 `post_build`。

2023-01-14 19:36 UTC, Y7n05h requested changes
4 个 lilac.yaml 的 `pre_build` 全都用的不对。除此之外，我没发现别的问题了。

2023-01-14 19:36 UTC, Y7n05h commented on archlinuxcn/libglibutil/lilac.yaml
> +pre_build: vcs_update
[vcs_update](https://lilac.readthedocs.io/en/latest/api.html#lilac2.api.vcs_update) 是给 `-git` 包这种用的。
```suggestion
pre_build_script: update_pkgver_and_pkgrel(_G.newver)
```

2023-01-14 19:36 UTC, Y7n05h commented on archlinuxcn/libgbinder/lilac.yaml
> +pre_build: vcs_update
[vcs_update](https://lilac.readthedocs.io/en/latest/api.html#lilac2.api.vcs_update) 是给 `-git` 包这种用的。
```suggestion
pre_build_script: update_pkgver_and_pkgrel(_G.newver)
```

2023-01-15 05:40 UTC, Puqns67 commented
第一次提交 Pull requests，有些不熟练，请见谅。

2023-01-15 06:17 UTC, Y7n05h approved these changes

2023-01-15 06:19 UTC, Y7n05h commented
> 第一次提交 Pull requests，有些不熟练，请见谅。

没什么的，做的很好了～

2023-01-15 06:27 UTC, merged