Add python-fontmake
archlinuxcn/repo pull request #3128
Opened 2023-01-27 12:19 UTC by taotieren

2023-01-29 01:52 UTC, Y7n05h requested changes
下面这些依赖不在官方源或 archlinuxcn 源里。缺失相关依赖，因此无法完成打包。
```
error: target not found: python-fontmath
error: target not found: python-glyphslib
error: target not found: python-ttfautohint-py
error: target not found: python-ufo2ft
error: target not found: python-compreffor
error: target not found: python-defcon
error: target not found: python-mutatormath
error: target not found: python-skia-pathops
```

2023-01-29 08:31 UTC, taotieren commented
> 下面这些依赖不在官方源或 archlinuxcn 源里。缺失相关依赖，因此无法完成打包。
> 
> ```
> error: target not found: python-fontmath
> error: target not found: python-glyphslib
> error: target not found: python-ttfautohint-py
> error: target not found: python-ufo2ft
> error: target not found: python-compreffor
> error: target not found: python-defcon
> error: target not found: python-mutatormath
> error: target not found: python-skia-pathops
> ```

好的，晚点抽空补齐这些包。

2023-01-30 03:10 UTC, taotieren commented
待续。后满还有一些包需要补齐。。。。。。

2023-02-02 02:25 UTC, Y7n05h requested changes
我目前只 review 了一部分。看起来有一些包，没法完成打包流程。这可能与你没有使用 devtools 来验证你的 PKGBUILD 有关。

请确保每一个 PKGBUILD 能通过 devtools 打包（需要安装 devtools-cn-git）。
在含有 PKGBUILD 的目录中执行 `extra-x86_64-build` 或 `archlinuxcn-x86_64-build` 就好。如果需要使用一个源里面没有的包可以通过参数 `-I PATH` 把本地包传进去。

更新：
突然发现我把 -I 的用法没说清楚，可能产生了歧义。举例说明一下：
```
extra-x86_64-build -- -I ../libglibutil/libglibutil-1.0.67-1-x86_64.pkg.tar.zst -I ../libgbinder/libgbinder-1.1.31-1-x86_64.pkg.tar.zst
```

2023-02-02 02:25 UTC, Y7n05h commented on archlinuxcn/python-skia-pathops-git/PKGBUILD
> +}
出错了。
```
==> Starting build()...
* Getting build dependencies for wheel...
/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)

ERROR Missing dependencies:
        setuptools_git_ls_files
```

2023-02-02 03:39 UTC, taotieren commented
> 我目前只 review 了一部分。看起来有一些包，没法完成打包流程。这可能与你没有使用 devtools 来验证你的 PKGBUILD 有关。
> 
> 请确保每一个 PKGBUILD 能通过 devtools 打包（需要安装 devtools-cn-git）。 在含有 PKGBUILD 的目录中执行 `extra-x86_64-build` 或 `archlinuxcn-x86_64-build` 就好。如果需要使用一个源里面没有的包可以通过参数 `-I PATH` 把本地包传进去。

好的，我按这个方式重新测试下。

2023-02-02 08:10 UTC, hubutui commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +}
这种是不是 `PYTHONPATH` 写错了．我好像没见过用 `Lib` 这样的路径的啊．@taotieren 多检查一下吧．如果打这个包需要太多的依赖包，你可以考虑先把他的依赖包打包成功并且添加进来，最后再打包你需要的这个包．

2023-02-02 08:16 UTC, hubutui commented on archlinuxcn/python-ufonormalizer-git/PKGBUILD
> +
建议参看 wiki 上的[打包指南](https://wiki.archlinux.org/title/Python_package_guidelines#Check)，一般需要设置 `PYTHONPATH` 的话就是用 `PYTHONPATH="$PWD/build/lib"` 或者 wiki 里带 CPU 架构的形式．得看你的 python 包是 any 包还是别的．

2023-02-02 08:37 UTC, taotieren commented on archlinuxcn/python-ufonormalizer-git/PKGBUILD
> +
好的我改改。  那个 `notepad---git` 可以合并了吧

2023-02-02 13:41 UTC, taotieren commented on archlinuxcn/python-ufonormalizer-git/PKGBUILD
> +
已修复
```bash
==> Retrieving sources...
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Creating working copy of python-ufonormalizer-git git repo...
Cloning into 'python-ufonormalizer-git'...
done.
==> Starting pkgver()...
==> Starting build()...
* Getting build dependencies for wheel...
/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
* Building wheel...
/usr/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
  warnings.warn(msg, warning_class)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/ufonormalizer
copying src/ufonormalizer/__init__.py -> build/lib/ufonormalizer
copying src/ufonormalizer/_version.py -> build/lib/ufonormalizer
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/ufonormalizer
copying build/lib/ufonormalizer/__init__.py -> build/bdist.linux-x86_64/wheel/ufonormalizer
copying build/lib/ufonormalizer/_version.py -> build/bdist.linux-x86_64/wheel/ufonormalizer
running install_egg_info
running egg_info
creating src/ufonormalizer.egg-info
writing src/ufonormalizer.egg-info/PKG-INFO
writing dependency_links to src/ufonormalizer.egg-info/dependency_links.txt
writing entry points to src/ufonormalizer.egg-info/entry_points.txt
writing top-level names to src/ufonormalizer.egg-info/top_level.txt
writing manifest file 'src/ufonormalizer.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'src/ufonormalizer.egg-info/SOURCES.txt'
Copying src/ufonormalizer.egg-info to build/bdist.linux-x86_64/wheel/ufonormalizer-0.6.1-py3.10.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/ufonormalizer-0.6.1.dist-info/WHEEL
creating '/build/python-ufonormalizer-git/src/python-ufonormalizer-git/dist/.tmp-ozq7l98q/ufonormalizer-0.6.1-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'ufonormalizer/__init__.py'
adding 'ufonormalizer/_version.py'
adding 'ufonormalizer-0.6.1.dist-info/LICENSE.txt'
adding 'ufonormalizer-0.6.1.dist-info/METADATA'
adding 'ufonormalizer-0.6.1.dist-info/WHEEL'
adding 'ufonormalizer-0.6.1.dist-info/entry_points.txt'
adding 'ufonormalizer-0.6.1.dist-info/top_level.txt'
adding 'ufonormalizer-0.6.1.dist-info/zip-safe'
adding 'ufonormalizer-0.6.1.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built ufonormalizer-0.6.1-py3-none-any.whl
==> Starting check()...
============================= test session starts ==============================
platform linux -- Python 3.10.9, pytest-7.2.1, pluggy-1.0.0
rootdir: /build/python-ufonormalizer-git/src/python-ufonormalizer-git
collected 143 items

tests/test_ufonormalizer.py ............................................ [ 30%]
........................................................................ [ 81%]
...........................                                              [100%]

============================= 143 passed in 1.21s ==============================
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "python-ufonormalizer-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: python-ufonormalizer-git 0.6.1.r0.g2d4c06c-1 (Thu Feb  2 21:40:18 2023)
==> Installing package python-ufonormalizer-git with pacman -U...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) python-ufonormalizer-git-0.6.1.r0.g2d4c06c-1

Total Installed Size:  0.13 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                    [####################################################################] 100%
(1/1) checking package integrity                                                                                  [####################################################################] 100%
(1/1) loading package files                                                                                       [####################################################################] 100%
(1/1) checking for file conflicts                                                                                 [####################################################################] 100%
:: Processing package changes...
(1/1) installing python-ufonormalizer-git                                                                         [####################################################################] 100%
resolving dependencies...
looking for conflicting packages...

Packages (5) elfutils-0.188-2  licenses-20220125-1  pyalpm-0.10.6-4  python-pyelftools-0.29-1  namcap-3.3.1-1

Total Download Size:   1.04 MiB
Total Installed Size:  6.04 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 elfutils-0.188-2-x86_64                                                              574.9 KiB  1032 KiB/s 00:01 [####################################################################] 100%
 python-pyelftools-0.29-1-any                                                         274.5 KiB  1476 KiB/s 00:00 [####################################################################] 100%
 namcap-3.3.1-1-any                                                                    97.2 KiB   657 KiB/s 00:00 [####################################################################] 100%
 licenses-20220125-1-any                                                               69.0 KiB  1533 KiB/s 00:00 [####################################################################] 100%
 pyalpm-0.10.6-4-x86_64                                                                46.2 KiB   632 KiB/s 00:00 [####################################################################] 100%
 Total (5/5)                                                                         1061.7 KiB   841 KiB/s 00:01 [####################################################################] 100%
(5/5) checking keys in keyring                                                                                    [####################################################################] 100%
(5/5) checking package integrity                                                                                  [####################################################################] 100%
(5/5) loading package files                                                                                       [####################################################################] 100%
(5/5) checking for file conflicts                                                                                 [####################################################################] 100%
:: Processing package changes...
(1/5) installing pyalpm                                                                                           [####################################################################] 100%
(2/5) installing licenses                                                                                         [####################################################################] 100%
(3/5) installing elfutils                                                                                         [############### [...]

2023-02-03 13:47 UTC, taotieren commented on archlinuxcn/python-ufonormalizer-git/PKGBUILD
> +license=('MIT')
已修复

2023-02-03 13:47 UTC, taotieren commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +}
已修复

2023-02-03 13:47 UTC, taotieren commented on archlinuxcn/python-skia-pathops-git/PKGBUILD
> +}
已修复

2023-02-03 13:48 UTC, taotieren commented
上传的包，全部经过 `archlinuxcn-x86_4-build` 编译测试。

2023-02-03 15:26 UTC, Y7n05h requested changes

2023-02-03 15:26 UTC, Y7n05h commented on archlinuxcn/python-ufonormalizer-git/PKGBUILD
> +    python -m installer -d "$pkgdir" dist/*.whl
没安装 LICENSE 文件。详细要求见 https://wiki.archlinux.org/title/PKGBUILD#license

2023-02-03 15:26 UTC, Y7n05h commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +    cd "$pkgname"
没安装 LICENSE 文件。详细要求见 https://wiki.archlinux.org/title/PKGBUILD#license

2023-02-03 15:26 UTC, Y7n05h commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +depends=(python-fonttools)
根据这个项目的 README:
>ttfautohint-py is a Python wrapper for [ttfautohint](https://www.freetype.org/ttfautohint)

那这个项目是否依赖 ttfautohint 呢？

2023-02-03 15:26 UTC, Y7n05h commented on archlinuxcn/python-skia-pathops-git/PKGBUILD
> +    python setup.py install --root="$pkgdir" --optimize=1 --skip-build
没安装 LICENSE 文件。详细要求见 https://wiki.archlinux.org/title/PKGBUILD#license

2023-02-03 15:26 UTC, Y7n05h commented on archlinuxcn/python-skia-pathops-git/lilac.yaml
> +build_prefix: extra-x86_64
`python-setuptools-git-ls-files` 在这个 pr 中包含，你需要用 archlinuxcn-x86_64

2023-02-03 16:36 UTC, Y7n05h commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +depends=(python-fonttools)
我恰好也用 ttfautohint，我把 ttfautohint 打包好了。

2023-02-04 02:56 UTC, hubutui commented on archlinuxcn/python-skia-pathops-git/lilac.yaml
> +build_prefix: extra-x86_64
现在不用 archlinuxcn-x86_64 了打包了啊，要写 repo_depends。
@taotieren 你可以参考这个包 [python-imagecodecs](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/python-imagecodecs/lilac.yaml)

2023-02-04 03:26 UTC, taotieren commented on archlinuxcn/python-ufonormalizer-git/PKGBUILD
> +    python -m installer -d "$pkgdir" dist/*.whl
`whl` 包里面带了一份 `LICENSE` 文件，不需要重复安装

2023-02-04 03:27 UTC, taotieren commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +depends=(python-fonttools)
你那边打包好了，我这里删掉这个包吧

2023-02-04 03:29 UTC, taotieren commented on archlinuxcn/python-skia-pathops-git/lilac.yaml
> +build_prefix: extra-x86_64
那是不是这些包要重新改一下呢？

2023-02-04 04:24 UTC, hubutui commented on archlinuxcn/python-skia-pathops-git/lilac.yaml
> +build_prefix: extra-x86_64
那是肯定的啊。这么多包慢慢搞吧。

2023-02-04 05:03 UTC, Y7n05h commented on archlinuxcn/python-skia-pathops-git/lilac.yaml
> +build_prefix: extra-x86_64
> 现在不用 archlinuxcn-x86_64 了打包了啊，要写 repo_depends。

@hubutui archlinuxcn-x86_64 和 repo_depends 都行的吧？这两个二选一就好了吧？

2023-02-04 06:19 UTC, taotieren commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +    cd "$pkgname"
```bash
repo/archlinuxcn/python-ttfautohint-py-git on  python-fontmake-git [?] 
❯ exa -T pkg                                                                                                     
pkg
└── python-ttfautohint-py-git
   └── usr
      └── lib
         └── python3.10
            └── site-packages
               ├── ttfautohint
               │  ├── __init__.py
               │  ├── __main__.py
               │  ├── __pycache__
               │  │  ├── __init__.cpython-310.opt-1.pyc
               │  │  ├── __init__.cpython-310.pyc
               │  │  ├── __main__.cpython-310.opt-1.pyc
               │  │  ├── __main__.cpython-310.pyc
               │  │  ├── _compat.cpython-310.opt-1.pyc
               │  │  ├── _compat.cpython-310.pyc
               │  │  ├── _version.cpython-310.opt-1.pyc
               │  │  ├── _version.cpython-310.pyc
               │  │  ├── cli.cpython-310.opt-1.pyc
               │  │  ├── cli.cpython-310.pyc
               │  │  ├── errors.cpython-310.opt-1.pyc
               │  │  ├── errors.cpython-310.pyc
               │  │  ├── info.cpython-310.opt-1.pyc
               │  │  ├── info.cpython-310.pyc
               │  │  ├── memory.cpython-310.opt-1.pyc
               │  │  ├── memory.cpython-310.pyc
               │  │  ├── options.cpython-310.opt-1.pyc
               │  │  ├── options.cpython-310.pyc
               │  │  ├── progress.cpython-310.opt-1.pyc
               │  │  └── progress.cpython-310.pyc
               │  ├── _compat.py
               │  ├── _version.py
               │  ├── cli.py
               │  ├── errors.py
               │  ├── info.py
               │  ├── memory.py
               │  ├── options.py
               │  └── progress.py
               └── ttfautohint_py-0.5.1.dist-info
                  ├── LICENSE
                  ├── METADATA
                  ├── RECORD
                  ├── top_level.txt
                  └── WHEEL

```

2023-02-04 06:29 UTC, taotieren commented on archlinuxcn/python-skia-pathops-git/lilac.yaml
> +build_prefix: extra-x86_64
> 那是肯定的啊。这么多包慢慢搞吧。

按这种方式已修改，可是 github 的 ci 测试失败。。。。

2023-02-04 06:39 UTC, taotieren commented on archlinuxcn/python-skia-pathops-git/PKGBUILD
> +    python setup.py install --root="$pkgdir" --optimize=1 --skip-build
已修复
```bash
repo/archlinuxcn/python-skia-pathops-git on  python-fontmake-git [!?] took 39s 
❯ exa -T pkg
pkg
└── python-skia-pathops-git
   └── usr
      ├── lib
      │  └── python3.10
      │     └── site-packages
      │        ├── pathops
      │        │  ├── __init__.py
      │        │  ├── __pycache__
      │        │  │  ├── __init__.cpython-310.opt-1.pyc
      │        │  │  ├── __init__.cpython-310.pyc
      │        │  │  ├── _version.cpython-310.opt-1.pyc
      │        │  │  ├── _version.cpython-310.pyc
      │        │  │  ├── operations.cpython-310.opt-1.pyc
      │        │  │  └── operations.cpython-310.pyc
      │        │  ├── _pathops.cpython-310-x86_64-linux-gnu.so
      │        │  ├── _version.py
      │        │  └── operations.py
      │        └── skia_pathops-0.7.5.dev4+g2e7c322-py3.10.egg-info
      │           ├── dependency_links.txt
      │           ├── not-zip-safe
      │           ├── PKG-INFO
      │           ├── requires.txt
      │           ├── SOURCES.txt
      │           └── top_level.txt
      └── share
         └── licenses
            └── python-skia-pathops
               └── LICENSE

```

2023-02-04 06:40 UTC, taotieren commented
> 我目前只 review 了一部分。看起来有一些包，没法完成打包流程。这可能与你没有使用 devtools 来验证你的 PKGBUILD 有关。
> 
> 请确保每一个 PKGBUILD 能通过 devtools 打包（需要安装 devtools-cn-git）。 在含有 PKGBUILD 的目录中执行 `extra-x86_64-build` 或 `archlinuxcn-x86_64-build` 就好。如果需要使用一个源里面没有的包可以通过参数 `-I PATH` 把本地包传进去。
> 
> 更新： 突然发现我把 -I 的用法没说清楚，可能产生了歧义。举例说明一下：
> 
> ```
> extra-x86_64-build -- -I ../libglibutil/libglibutil-1.0.67-1-x86_64.pkg.tar.zst -I ../libgbinder/libgbinder-1.1.31-1-x86_64.pkg.tar.zst
> ```

多谢，能看懂，

2023-02-04 10:53 UTC, hubutui commented on archlinuxcn/python-skia-pathops-git/lilac.yaml
> +build_prefix: extra-x86_64
@Y7n05h 见 https://github.com/archlinuxcn/repo/issues/1073

2023-02-04 11:22 UTC, taotieren commented on archlinuxcn/python-skia-pathops-git/lilac.yaml
> +build_prefix: extra-x86_64
是的，现在改了，但是 Github CI 失败，影响合并吗？

2023-02-04 12:02 UTC, Y7n05h commented on archlinuxcn/python-skia-pathops-git/lilac.yaml
> +build_prefix: extra-x86_64
> @Y7n05h 见 #1073

感谢。我之前不知道存在这个共识。

2023-02-04 14:46 UTC, hubutui commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +    cd "$pkgname"
这里的意思是要求把不在 [licenses]() 这个包里的许可证文件都要用类似 `install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"` 的命令安装到 `"$pkgdir/usr/share/licenses/$pkgname/LICENSE"`. 具体到这个包，你需要把 `/usr/lib/python3.10/site-packages/ttfautohint_py-0.5.1.dist-info/LICENSE` 复制到指定的路径去。

2023-02-04 14:48 UTC, hubutui commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +    python setup.py test
包检查一般用 `pytest -v` 就好了吧，然后根据需要设置 `PYTHONPATH`。这部分可以参考 Python 的[打包指南](https://wiki.archlinux.org/title/Python_package_guidelines)。

2023-02-04 14:49 UTC, hubutui commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +              python-wheel
这里你想要好看一点可以考虑一行写一个，然后排个序。当然，目前这个不算啥问题。

2023-02-04 14:53 UTC, hubutui commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +    python setup.py test
另外，我测试了一下用 `pytest -v` 跑的话，会提示缺了 `libttfautohint.so`。而根据[文档](https://github.com/fonttools/ttfautohint-py)，如果你从 PyPI 安装 wheel 包，那就有自带的 ttfautohint 的动态库文件。这里我们从源码打包的话，就需要加上 ttfautohint 这个依赖。因此应该还需要打包 ttfautohint 这个包。

2023-02-04 14:57 UTC, hubutui commented
另外，虽然你想要打的包是 `python-fontmake-git`，但是并不是说它依赖的那些包都要打 `-git` 包的。一般来说，建议打个普通的发行版本的包就可以了，包括 `python-fontmake`。如果打 `-git` 包，也可以考虑设置 `lilac_throttle`，避免过于频繁的打包。这部分可以在仓库里搜一下 `lilac_throttle`，看看其他 `-git` 包的设置。

2023-02-04 14:59 UTC, hubutui commented
另外，你可能是没有设置 precommit hook？设置好之后可以在你提交的时候做一些检查，检查不通过就不会成功提交。比如说缺了 `repo_depends` 之类的。

2023-02-04 16:04 UTC, Y7n05h commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +depends=(python-fonttools)
根据 ttfautohint-py 的 [README](https://github.com/fonttools/ttfautohint-py/blob/main/README.rst)：

> ttfautohint-py is a Python wrapper for [ttfautohint](https://www.freetype.org/ttfautohint), a free auto-hinter for TrueType fonts created by Werner Lemberg ([@lemzwerg](https://github.com/lemzwerg)).
> 
> It uses [ctypes](https://docs.python.org/3/library/ctypes.html) to load the libttfautohint shared library and call the TTF_autohint function.

这里 ttfautohint-py 只是 ttfautohint 的包装器。是通过 FFI 来调用 libttfautohint 的。因此 ttfautohint-py 必然依赖 ttfautohint。

2023-02-04 16:29 UTC, hubutui commented
check 这部分应该用 `pytest` 或者 `nosetest`，参考[打包指南](https://wiki.archlinux.org/title/Python_package_guidelines#Check)。`python setup.py test` 这种用法是 deprecated 的，见 https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#do-not-run-via-setuptools

2023-02-05 05:28 UTC, taotieren commented
> BTW，你可能是没有设置 precommit hook？设置好之后可以在你提交的时候做一些检查，检查不通过就不会成功提交。比如说缺了 `repo_depends` 之类的。

确实没有设置这个，有参考设置吗？

2023-02-05 05:48 UTC, hubutui commented
> > BTW，你可能是没有设置 precommit hook？设置好之后可以在你提交的时候做一些检查，检查不通过就不会成功提交。比如说缺了 `repo_depends` 之类的。
> 
> 确实没有设置这个，有参考设置吗？

你直接搜一个呗，这仓库里肯定有很多包有这些的。比如 [python-imagecodecs](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/python-imagecodecs/lilac.yaml)

2023-02-05 05:56 UTC, taotieren commented
> > > BTW，你可能是没有设置 precommit hook？设置好之后可以在你提交的时候做一些检查，检查不通过就不会成功提交。比如说缺了 `repo_depends` 之类的。
> > 
> > 
> > 确实没有设置这个，有参考设置吗？
> 
> 你直接搜一个呗，这仓库里肯定有很多包有这些的。比如 [python-imagecodecs](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/python-imagecodecs/lilac.yaml)

仓库里面的 `pre-commit` hook 怎么配置的呢

2023-02-05 06:00 UTC, imlonghao commented
> > > > BTW，你可能是没有设置 precommit hook？设置好之后可以在你提交的时候做一些检查，检查不通过就不会成功提交。比如说缺了 `repo_depends` 之类的。
> > > 
> > > 
> > > 确实没有设置这个，有参考设置吗？
> > 
> > 
> > 你直接搜一个呗，这仓库里肯定有很多包有这些的。比如 [python-imagecodecs](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/python-imagecodecs/lilac.yaml)
> 
> 仓库里面的 `pre-commit` hook 怎么配置的呢

https://github.com/archlinuxcn/repo/blob/master/pre-commit#L3-L16

2023-02-05 06:03 UTC, taotieren commented
> > > > > BTW，你可能是没有设置 precommit hook？设置好之后可以在你提交的时候做一些检查，检查不通过就不会成功提交。比如说缺了 `repo_depends` 之类的。
> > > > 
> > > > 
> > > > 确实没有设置这个，有参考设置吗？
> > > 
> > > 
> > > 你直接搜一个呗，这仓库里肯定有很多包有这些的。比如 [python-imagecodecs](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/python-imagecodecs/lilac.yaml)
> > 
> > 
> > 仓库里面的 `pre-commit` hook 怎么配置的呢
> 
> https://github.com/archlinuxcn/repo/blob/master/pre-commit#L3-L16

注释中的这一行 ` ln -s ../../pre-commit .git/hooks` 是不是配置有问题。

2023-02-05 06:05 UTC, imlonghao commented
> 注释中的这一行 ` ln -s ../../pre-commit .git/hooks` 是不是配置有问题。

没有问题

2023-02-05 07:01 UTC, Y7n05h commented
> 注释中的这一行 ` ln -s ../../pre-commit .git/hooks` 是不是配置有问题。

这个命令需要在你 clone 下来的仓库的根目录中执行。你需要先 cd 过去。

2023-02-05 13:18 UTC, taotieren commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +    cd "$pkgname"
已修复

2023-02-05 13:18 UTC, taotieren commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +depends=(python-fonttools)
已修复

2023-02-05 13:18 UTC, taotieren commented on archlinuxcn/python-ufonormalizer-git/PKGBUILD
> +    python -m installer -d "$pkgdir" dist/*.whl
已修复

2023-02-06 07:32 UTC, Y7n05h commented on archlinuxcn/python-ufonormalizer-git/PKGBUILD
> +    install -Dm644 LICENSE.txt "$pkgdir/usr/share/licenses/${pkgname%-git}/LICENSE"
安装 license 文件的路径是错的。
/usr/share/licenses/$pkgname/
也就是 "/usr/share/licenses/python-ufonormalizer-git/" 而不是 "/usr/share/licenses/python-ufonormalizer/"
不该去掉 `-git` 后缀。

2023-02-06 07:40 UTC, Y7n05h commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +depends=(python-fonttools
namcap 的报错：
```
python-ttfautohint-py-git E: Dependency python-setuptools detected and not included (libraries ['pkg_resources'] needed in files ['usr/lib/python3.10/site-packages/ttfautohint/_version.py'])
```

2023-02-06 07:46 UTC, Y7n05h commented
ci 没过我猜是因为 repo_depends 里面只能用 pkgname ，而不支持 provide 这种机制。

2023-02-06 08:03 UTC, hubutui commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +depends=(python-fonttools
有必要把 `python-setuptools` 加到 depends 里么？虽然他有这个提示，但是我一般还是不加的．我感觉这个问题不大．

2023-02-06 08:06 UTC, hubutui commented
> 

其实我前面就有说了，一般来说没有特殊需要的话，不用打 `-git` 包．即使打 `-git` 包，也不代表这个包依赖的那些包都要打 `-git` 包．

PS：真的佩服这毅力，这么多依赖包，是我的话干脆就不打了．

建议安装好 `namcap`，使用 devtools 打包最后会自动进行包的检查，注意查看这些提示，根据提示修改好再提交吧．不然这个 review 到啥时候啊．这里指出的问题基本上是每个包都要检查的，返工一次也很耗费精力的．

2023-02-06 08:11 UTC, Y7n05h commented on archlinuxcn/python-ttfautohint-py-git/PKGBUILD
> +depends=(python-fonttools
嗯，这个我也不确定。（先就这样吧。

2023-02-06 08:17 UTC, Y7n05h commented
> 一般来说没有特殊需要的话，不用打 `-git` 包．即使打 `-git` 包，也不代表这个包依赖的那些包都要打 `-git` 包．

他可能误会了什么。https://github.com/archlinuxcn/repo/pull/3141#issuecomment-1411385020
我猜他可能觉得非 `-git` 是被保留给官方仓库的。

> PS：真的佩服这毅力，这么多依赖包，是我的话干脆就不打了．

同感。我当初也提及过替代方案。https://github.com/archlinuxcn/repo/pull/3031#issuecomment-1407537148

2023-02-06 13:53 UTC, taotieren commented
> > 
> 
> 其实我前面就有说了，一般来说没有特殊需要的话，不用打 `-git` 包．即使打 `-git` 包，也不代表这个包依赖的那些包都要打 `-git` 包．
> 
> PS：真的佩服这毅力，这么多依赖包，是我的话干脆就不打了．
> 
> 建议安装好 `namcap`，使用 devtools 打包最后会自动进行包的检查，注意查看这些提示，根据提示修改好再提交吧．不然这个 review 到啥时候啊．这里指出的问题基本上是每个包都要检查的，返工一次也很耗费精力的．

现在疑惑的是用不用 `-git` 包呢？还是其他方式呢？但是用 -I *-git* 这种方式来编译是可以通过的。

2023-02-06 14:43 UTC, Y7n05h commented
> 现在疑惑的是用不用 `-git` 包呢？还是其他方式呢？

没看懂这句话在表达什么。
我们所说的不打 `-git` 包是指***不***使用 git 仓库中的最新提交来打包。而是使用上游发布的版本来打包（包含 github release,git tag,pypi 等多种渠道）。

> 用 -I \*-git\* 这种方式来编译是可以通过的。

我们不是在表达你打的包无法完成构建。我们是在表达，在非 `-git` 包能满足需求的情况下，打包 `-git` 的包不是个好选择。

关于 `-git` 包的问题，你可以参考下仓库里的 yay-git 和 yay 的 PKGBUILD 的区别。

2023-02-06 14:44 UTC, hubutui commented
> > 一般来说没有特殊需要的话，不用打 `-git` 包．即使打 `-git` 包，也不代表这个包依赖的那些包都要打 `-git` 包．
> 
> 他可能误会了什么。[#3141 (comment)](https://github.com/archlinuxcn/repo/pull/3141#issuecomment-1411385020) 我猜他可能觉得非 `-git` 是被保留给官方仓库的。
> 
没有这回事吧。官方是否收录某个包主要取决于有没有 TU 去添加这个包。
> > PS：真的佩服这毅力，这么多依赖包，是我的话干脆就不打了．
> 
> 同感。我当初也提及过替代方案。[#3031 (comment)](https://github.com/archlinuxcn/repo/pull/3031#issuecomment-1407537148)

打这么多报就只是为了成功打那个字体包？字体包没有必要从源码编译吧，直接用二进制包就好了。参考一下官方仓库里的字体包如何打包的。

2023-02-07 15:22 UTC, hubutui commented
具体文件 review 提到的问题都不是个例，请检查所有的文件看看是否有问题。

2023-02-08 13:54 UTC, taotieren commented on archlinuxcn/python-ufonormalizer-git/PKGBUILD
> +    install -Dm644 LICENSE.txt "$pkgdir/usr/share/licenses/${pkgname%-git}/LICENSE"
已修复

2023-02-08 13:56 UTC, taotieren commented
> 具体文件 review 提到的问题都不是个例，请检查所有的文件看看是否有问题。
现在改成 py 包了，获取最新 py 包部分帮忙看看，有没有问题，本地测试是通过的，

2023-02-08 15:25 UTC, taotieren commented
> 我前面具体写的修改意见，你是一个都没有改也没有解释啊。 本地测试我不知道你怎么测试的，请参考[打包指南](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)在一个干净的 chroot 环境打包测试。

使用的是  `extra-x86_64-build -- -I ` 的方式测试

2023-02-09 06:26 UTC, hubutui commented
你这一次性添加的包太多了．麻烦给个正确的打包顺序，我们才好检查测试．

2023-02-09 06:30 UTC, Y7n05h commented
建议把全部依赖已存在于源里的包全都拆到另一个 pr 里面去。

2023-02-09 06:38 UTC, hubutui commented
或者简单的一个 pr 添加一个包就好了嘛，按顺序来，加好一个再下一个．

2023-02-09 06:44 UTC, hubutui commented
至少有以下几项通用的需要修改的地方：
1. 优先使用 PEP 517 的方式打包，参考[文档](https://wiki.archlinux.org/title/Python_package_guidelines#Installation_methods)，然后才是 legacy setuptools．
2. 请保持代码的缩进对齐，统一好使用空格缩进．
3. 确认局部变量 `python_version` 是已经定义的，参考[文档](https://wiki.archlinux.org/title/Python_package_guidelines#Using_python_version)．
4. 确认许可证的名字，以及这个许可证是否包含在 [licenses](https://archlinux.org/packages/core/any/licenses/) 中，未包含的需要将其打包．
5. 源码不是 git repo 的不需要执行 `git submodule` 命令啊．

2023-02-09 10:29 UTC, yan12125 commented
這些包有 circular dependency, lilac 沒辦法處理: python-booleanoperations -> python-fontpens -> python-fontparts -> python-booleanoperations. See: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-booleanoperations#n37

2023-02-09 12:06 UTC, hubutui commented
@yan12125 你是怎么看出来的啊。我看包太多了都不方便看了。

2023-02-09 15:01 UTC, yan12125 commented
AUR 包 python-booleanoperations 的註解有提到 circular dependencies, 我才回來看的。

2023-09-18 23:14 UTC, auxiliarypower commented
I have added the python-fontmake package to the repository, pull request can be closed. Check out #3467.

2023-10-12 06:38 UTC, auxiliarypower commented
I don’t want to maintain this package anymore, because it has too many dependencies. If you want to continue maintaining it, I will reopen this pull request.

2023-10-12 07:22 UTC, auxiliarypower requested changes
The following Python packages, python-booleanoperations, python-defcon, python-fontmath, python-fontparts, python-fontpens, python-mutatormath and python-pyclipper, are available in the official repositories.

2025-03-12 03:55 UTC, taotieren commented
相关包本地编译不通过，已放弃。

2025-03-12 03:55 UTC, closed without merging