Update notepad---git
archlinuxcn/repo pull request #3200
Opened 2023-03-07 07:18 UTC by taotieren

- 修复 notepad-- 编译错误

2023-03-07 09:59 UTC, taotieren commented
@hubutui 帮忙合并下？谢谢。

2023-03-08 04:29 UTC, Y7n05h requested changes

2023-03-08 04:29 UTC, Y7n05h commented on archlinuxcn/notepad---git/PKGBUILD
> +provides=(${pkgname%-git} notepadplugin NotepadPlugin)
provides 不该包含大写字符

2023-03-08 04:29 UTC, Y7n05h commented on archlinuxcn/notepad---git/PKGBUILD
> +source=("${pkgname}::git+${url}.git#branch=cmake-dev")
既然这里指定 cmake-dev 分支，那么 lilac.yaml 也需要修改来指定 cmake-dev 分支。

2023-03-10 03:14 UTC, taotieren commented on archlinuxcn/notepad---git/PKGBUILD
> +provides=(${pkgname%-git} notepadplugin NotepadPlugin)
已修复

2023-03-10 03:15 UTC, taotieren commented on archlinuxcn/notepad---git/PKGBUILD
> +source=("${pkgname}::git+${url}.git#branch=cmake-dev")
已增加

2023-03-10 03:35 UTC, Y7n05h requested changes

2023-03-10 03:35 UTC, Y7n05h commented on archlinuxcn/notepad---git/lilac.yaml
> +    git: https://gitee.com/cxasm/notepad--.git#branch=cmake-dev
lilac.yaml 不接受这样的语法。
在这里使用 branch 字段来修改。
文档：https://nvchecker.readthedocs.io/en/latest/usage.html#check-git-repository

2023-03-10 06:42 UTC, taotieren commented on archlinuxcn/notepad---git/lilac.yaml
> +    git: https://gitee.com/cxasm/notepad--.git#branch=cmake-dev
已按规范更新

2023-03-10 13:37 UTC, merged