addpkg: serenity
archlinuxcn/repo pull request #3939
Opened 2024-07-14 08:56 UTC by Misaka13514

[serenity](https://github.com/SagerNet/serenity): The configuration generator for sing-box

https://aur.archlinux.org/packages/serenity

## log

- [PKGBUILD-namcap.log](https://github.com/user-attachments/files/16216186/PKGBUILD-namcap.log)
- [serenity-1.0.0_beta.13-2-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/16216187/serenity-1.0.0_beta.13-2-x86_64.pkg.tar.zst-namcap.log)
- [serenity-1.0.0_beta.13-2-x86_64-build.log](https://github.com/user-attachments/files/16216188/serenity-1.0.0_beta.13-2-x86_64-build.log)
- [serenity-1.0.0_beta.13-2-x86_64-check.log](https://github.com/user-attachments/files/16216189/serenity-1.0.0_beta.13-2-x86_64-check.log)
- [serenity-1.0.0_beta.13-2-x86_64-package.log](https://github.com/user-attachments/files/16216190/serenity-1.0.0_beta.13-2-x86_64-package.log)
- [serenity-1.0.0_beta.13-2-x86_64-prepare.log](https://github.com/user-attachments/files/16216191/serenity-1.0.0_beta.13-2-x86_64-prepare.log)
- [serenity-debug-1.0.0_beta.13-2-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/16216192/serenity-debug-1.0.0_beta.13-2-x86_64.pkg.tar.zst-namcap.log)

## namcap

```
serenity W: ELF file ('usr/bin/serenity') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
serenity E: custom:GPL-3.0-or-later WITH name use or association addition is an invalid license string.
serenity-debug W: Directory (usr/src/debug/serenity) is empty
```

2024-07-18 16:23 UTC, rocka commented
`pacman` would consider `1.0.0_beta` to be newer than `1.0.0`. You can verify this by running `vercmp`:

```console
$ vercmp 1.0.0 2.0.0
-1
$ vercmp 1.0.0_beta 1.0.0
1
$ vercmp 1.0.0beta 1.0.0
-1
```

Since the package has not released a stable version yet, I suggest use a separate `_tagname` variable and instruct lilac to update that variable, like this:

https://github.com/archlinuxcn/repo/blob/cfba770e35a8b7ab3f4ef3bbbdb648c2e69734fc/archlinuxcn/ttf-blobmoji/PKGBUILD#L3-L13

https://github.com/archlinuxcn/repo/blob/cfba770e35a8b7ab3f4ef3bbbdb648c2e69734fc/archlinuxcn/ttf-blobmoji/lilac.yaml#L1-L7

2024-07-18 16:28 UTC, rocka requested changes

2024-07-18 16:28 UTC, rocka commented on archlinuxcn/serenity/PKGBUILD
> +pkgrel=2
Why `pkgrel=2` not `1`?

2024-07-18 16:28 UTC, rocka commented on archlinuxcn/serenity/PKGBUILD
> +license=('custom:GPL-3.0-or-later WITH name use or association addition')
The license file should be installed to `/usr/share/licenses/serenity/LICENSE` since it's a custom license.

2024-07-18 16:28 UTC, rocka commented on archlinuxcn/serenity/lilac.yaml
> +build_prefix: extra-x86_64
```suggestion
```

`extra-x86_64` is the default

2024-07-25 15:46 UTC, rocka requested changes

2024-07-26 00:49 UTC, Misaka13514 commented
Sorry I missed that comment. Thank you for the review.

2024-07-26 13:58 UTC, rocka approved these changes
LGTM

2024-07-26 13:59 UTC, merged

2024-07-26 14:34 UTC, rocka commented
This package was "updated" from `1.0.0beta.17` to `1.0.0beta.13` in https://github.com/archlinuxcn/repo/commit/e571a8caad7e55f6e5720bd92d90eebb6bc5a59d , apparently I've missed something.

As of now (2024-07-26 22:25), https://github.com/SagerNet/serenity/releases/latest points to `v1.0.0-beta.13` despite there is a newer version `1.0.0-beta.17`. Only release `v1.0.0-beta.13` has `v` prefix.

As for tags, https://github.com/SagerNet/serenity/releases/tag/v1.0.0-beta.15 and https://github.com/SagerNet/serenity/releases/tag/v1.0.0-beta.16 have tags but not release. https://github.com/SagerNet/serenity/releases/tag/1.0.0-beta.11 does not have `v` prefix, while all other tags seems to have. Maybe nvchecker config should be changed:

```yaml
update_on:
  - source: github
    github: SagerNet/serenity
    use_max_tag: true
    prefix: v
```